### ISSUE TITLE
http://inter-mediator.info/ja/for-novices/deploy6.html内のリンク切れ

### ISSUE THREAD

**Issue by iMiyuki** [INTER-Mediator/INTER-Mediator_WebSite#39]
Ver.5以前のページへのリンク先がdeployt.htmlになってます。
deploy.htmlが正しいのかと。

**Comment by msyk** [comment]
ありがとうございます。直しました。

**Comment by iMiyuki** [comment]
確認しました。ありがとうございます。
(次があれば修正したページをPullリクエストしたいなぁ。。。)
